# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trackmsg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='test-fence-tria', max_length=50)),
                ('vertices', trackmsg.models.ListField(help_text='vertices of polygon', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False)),
                ('coordinate', trackmsg.models.ListField(help_text='coordinates of the message', max_length=100)),
                ('alerted', models.BooleanField(default=False)),
                ('geo_fence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trackmsg.GeoFence')),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='tag name for tracker, \t\thas to be unique and can only contain characters, underscores and numbers', max_length=50, unique=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('active', models.BooleanField(default=False, help_text='Sets this tracker to active tracking')),
                ('url', models.SlugField(help_text='the url for this tracker will be /track/<url>', unique=True)),
                ('geo_fences', models.ManyToManyField(to='trackmsg.GeoFence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackmsg.Tracker'),
        ),
    ]
