# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackmsg', '0002_auto_20170302_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='label',
            field=models.CharField(default='test-fence-tria', max_length=50),
        ),
    ]
